openapi: 3.0.0
info:
  title: Bank Account Service
  description: API to manage bank accounts.
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Local server

paths:
  /v1/accounts:
    get:
      summary: Get all accounts
      operationId: getAllAccounts
      parameters:
        - name: clientId
          in: query
          required: false
          description: Id of client
          schema:
            type: string
        - name: type
          in: query
          required: false
          description: type
          schema:
            type: string
        - name: accountId
          in: query
          required: false
          description: Id of account
          schema:
            type: string
      responses:
        '200':
          description: List of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new account
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
      responses:
        '201':
          description: Account created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/accounts/{accountId}:
    get:
      summary: Get an account by ID
      operationId: getAccountById
      parameters:
        - name: accountId
          in: path
          required: true
          description: Id of account
          schema:
            type: string
      responses:
        '200':
          description: Account found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update an account by ID
      operationId: updateAccount
      parameters:
        - name: accountId
          in: path
          required: true
          description: Id of account
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
      responses:
        '200':
          description: Account updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete an account by ID
      operationId: deleteAccount
      parameters:
        - name: accountId
          in: path
          required: true
          description: Id of account
          schema:
            type: string
      responses:
        '204':
          description: Account deleted
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/accounts/{accountId}/withdrawal:
    post:
      summary: Make a withdraw from an account
      operationId: withdrawFromAccount
      parameters:
        - name: accountId
          in: path
          required: true
          description: Id of account
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawalRequest'
      responses:
        '200':
          description: Withdrawal made
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Insufficient funds
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/accounts/{accountId}/deposit:
    post:
      summary: Make a deposit to an account
      operationId: depositToAccount
      parameters:
        - name: accountId
          in: path
          required: true
          description: Id of account
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositRequest'
      responses:
        '200':
          description: Deposit made
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Insufficient deposit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/accounts/{accountId}/transfer:
    post:
      summary: Make a transfer to an account
      operationId: transferToAccount
      parameters:
        - name: accountId
          in: path
          required: true
          description: Id of account
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '200':
          description: Deposit made
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Insufficient balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/accounts/balance/{action}:
    post:
      summary: Make a transfer to an account
      operationId: handleBalanceAction
      parameters:
        - name: action
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BalanceRequest'
      responses:
        '200':
          description: Balance adjusted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountBalanceResponse'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Insufficient balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/accounts/{accountId}/balance:
    get:
      summary: Get client balances
      operationId: getClientBalances
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Client balances
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '404':
          description: Client not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/accounts/{accountId}/transactions:
    get:
      summary: Get client transactions
      operationId: getAccountIdTransactions
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of Transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionResponse'
        '404':
          description: Client not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    AccountRequest:
      type: object
      properties:
        type:
          type: string
          enum: [SAVINGS, CHECKING, FIXED_TERM]
        balance:
          type: number
        currency:
          type: string
        isActive:
          type: boolean
        movementLimit:
          type: integer
        maintenanceFee:
          type: number
        commissionFee:
          type: number
        authorizedSigners:
          type: array
          items:
            type: string
        holders:
          type: array
          items:
            type: string
        transactionDay:
          type: string
          format: date
          example: 2024-12-01
        clientId:
          type: string
      required:
        - type
        - clientId
        - isActive
        - currency
    AccountResponse:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum: [SAVINGS, CHECKING, FIXED_TERM]
        balance:
          type: object
        accountNumber:
          type: string
        createdDate:
          type: string
          format: date-time
        movementLimit:
          type: integer
        maintenanceFee:
          type: number
        commissionFee:
          type: number
        clientId:
          type: string
        transactionDay:
          type: string
          format: date
        holders:
          type: array
          items:
            type: string
        authorizedSigners:
          type: array
          items:
            type: string
    TransferRequest:
      type: object
      required:
        - amount
        - destinationProductId
      properties:
        destinationProductId:
          type: string
        amount:
          type: number
          format: double
    WithdrawalRequest:
      type: object
      required:
        - amount
      properties:
        amount:
          type: number
          format: double
    DepositRequest:
      type: object
      required:
        - amount
      properties:
        amount:
          type: number
          format: double
    TransactionRequest:
      type: object
      required:
        - productId
        - clientId
        - amount
      properties:
        productId:
          type: string
        destinationProductId:
          type: string
        type:
          type: string
          enum: [ DEPOSIT , WITHDRAWAL]
        amount:
          type: number
          format: double
        clientId:
          type: string
        commission:
          type: number
          format: double
        balance:
          type: number
          format: double
    TransactionResponse:
      type: object
      required:
        - id
        - productId
        - destinationProductId
        - type
        - amount
        - clientId
      properties:
        id:
          type: string
        productId:
          type: string
        destinationProductId:
          type: string
        type:
          type: string
          enum: [ DEPOSIT , WITHDRAWAL]
        amount:
          type: number
        clientId:
          type: string
    BalanceResponse:
      type: object
      properties:
        accountId:
          type: string
        clientId:
          type: string
        accountBalance:
          type: decimal
    BalanceRequest:
      type: object
      properties:
        accountId:
          type: string
        amount:
          type: decimal
    AccountBalanceResponse:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum: [SAVINGS, CHECKING, FIXED_TERM]
        balance:
          type: object
        status:
          type: string
          enum: [ COMPLETED, FAILED ]
        accountNumber:
          type: string
        clientId:
          type: string
    ErrorResponse:
      type: object
      required:
        - status
        - code
        - message
        - timestamp
      properties:
        status:
          type: int
        code:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
    Customer:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
          enum: [ PERSONAL, BUSINESS ]
        profile:
          type: string
          enum: [ VIP, PYME ]
        documentId:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
        address:
          type: string
    Credit:
      type: object
      properties:
        _id:
          type: string
        creditNumber:
          type: string
        type:
          type: string
          enum: [ PERSONAL, BUSINESS ]
        creditLimit:
          type: decimal
        consumptionAmount:
          type: decimal
        balance:
          type: decimal
        interestRate:
          type: decimal
        clientId:
          type: string
        createdDate:
          type: string
          format: date-time
